# .air.toml
[build]
cmd = "go build -o tmp/main -buildvcs=false ."
bin = "tmp/main"
full_bin = "tmp/main"
delay = 1000
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"